// <auto-generated />
namespace Syntra.VDOAP.CProef.ECommerce.LIB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productedit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productedit));
        
        string IMigrationMetadata.Id
        {
            get { return "201805081024412_product edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
